pages/urls.py
# Copyright (c) 2014, DjaoDjin inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


from django.conf.urls import patterns, url
from pages.api import PageElementDetail, FileUploadView
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^editables/upload-image/',
    	FileUploadView.as_view(), name='upload_image_element'),
    url(r'^editables/(?P<slug>[\w-]+)/',
    	PageElementDetail.as_view(), name='edit_page_element'),
)

testsite/urls.py
# Copyright (c) 2016, Djaodjin Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
import debug_toolbar

from pages.views.pages import PageView


urlpatterns = staticfiles_urlpatterns() \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^', include('pages.urls')),
    url(r'^$', PageView.as_view(template_name='index.html')),
    url(r'^app/$', TemplateView.as_view(template_name='index.html')),
]

pages/urls/views/editables.py
# Copyright (c) 2022, Djaodjin Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from ... import settings
from ...compat import re_path
from ...views.elements import PageElementEditableView

urlpatterns = [
    re_path(r'^(?P<path>%s)' % settings.PATH_RE,
        PageElementEditableView.as_view(), name='pages_editables_element'),
    re_path(r'^',
        PageElementEditableView.as_view(), name='pages_editables_index'),
]

pages/urls/views/progress.py
# Copyright (c) 2022, Djaodjin Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from ...compat import re_path
from ...views.progress import SequenceProgressView, SequencePageElementView
from ... import settings

app_name = 'progress'

urlpatterns = [
    re_path(r'^(?P<sequence_slug>%s)$' % settings.SLUG_RE,
            SequenceProgressView.as_view(),
            name='progress_view'),
    re_path(r'^(?P<sequence_slug>%s)/(?P<rank>\d+)$' % settings.SLUG_RE,
            SequencePageElementView.as_view(),
            name='page_element_view'),
]

pages/templates/pages/_comments.html
<div>
  <h4>[[comments.count]] Comments</h4>
  <table>
    <tr :id="'comment_from_'+ comment.user" v-for="comment in comments.results">
      <td>
        [[comment.user]]<br />
        <small>[[comment.created_at]]</small>
      </td>
      <td >[[comment.text]]</td>
    </tr>
  </table>
  {% if user.is_authenticated %}
  <form id="form_comment" action="." method="POST"
        @submit.prevent="submitComment($event)">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
    <textarea id="id_comment" cols="40" rows="10" name="comment" v-model="message"></textarea>
    <input type="submit" />
  </form>
  {% else %}
  <p>Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
  {% endif %}
</div>

pages/templates/pages/_follow_vote.html
<div style="display: inline-block;">
  <button type="submit"
    @click="submitFollow()" v-if="itemLoaded && item.follow">Unfollow</button>
  <button class="dj-answers-follow" type="submit"
    @click="submitFollow()" v-if="itemLoaded && !item.follow">Follow</button>
  <button class="dj-answers-upvote" type="submit"
    @click="submitVote()" v-if="itemLoaded && !item.upvote">Upvote</button>
  <button type="submit"
    @click="submitVote()" v-if="itemLoaded && item.upvote">Reset vote</button>
  <a id="nb-follows"
     class="disabled" v-if="itemLoaded">[[nbFollowers]] followers</a>
  <a id="nb-votes"
     class="disabled" v-if="itemLoaded">[[nbUpVotes]] upvotes</a>
</div>

pages/templates/pages/certificate.html
<!DOCTYPE html>
<html>
<head>
    <title>Certificate of Completion</title>
</head>
<body>
{{ certificate.text|safe }}
    <div class="certificate">
        <div>Certificate of Completion</div>
        <div>This is to certify that</div>
        <div>{{ user.username }}</div>
        <div>
            has successfully completed the <strong>{{ sequence.title }}</strong> sequence.
        </div>
        <div>Date: {{ completion_date|date:"F j, Y" }}</div>
    </div>
</body>
</html>

pages/templates/pages/editables.html
{% extends "pages/index.html" %}

pages/templates/pages/edition_tools.html
{% load static from staticfiles %}

<link rel="stylesheet" href="{% static 'vendor/css/djaodjin-editor.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'vendor/css/djaodjin-sidebar-gallery.css' %}" type="text/css" />
<link rel="stylesheet" href="{% static 'vendor/css/font-awesome.css' %}"/>
<link rel="stylesheet" href="{% static 'vendor/css/jquery-ui.css' %}"/>
<script src="{% static 'vendor/js/jquery.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/js/dropzone.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/js/jquery-ui.js' %}"></script>
<script src="{% static 'vendor/js/jquery.ui.touch-punch.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/js/rangy-core.js' %}"></script>
<script src="{% static 'vendor/js/hallo.js' %}"></script>
<script src="{% static 'vendor/js/rangy-core.js' %}"></script>
<script src="{% static 'vendor/js/Markdown.Converter.js' %}"></script>
<script src="{% static 'vendor/js/Markdown.Sanitiser.js' %}"></script>
<script src="{% static 'vendor/js/jquery.textarea_autosize.js' %}"></script>
<script src="{% static 'vendor/js/jquery.selection.js' %}"></script>
<script src="{% static 'vendor/js/djaodjin-editor.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/js/djaodjin-upload.js' %}" type="text/javascript"></script>
<script src="{% static 'vendor/js/djaodjin-sidebar-gallery.js' %}" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('.editable').editor({
            baseUrl: "{% url 'page_elements' %}",
        });

        $.djgallery({
            mediaUrl: "{% url 'uploaded_media_elements' %}",
            csrfToken: "{{csrf_token}}",
        });
    });
</script>

pages/templates/pages/index.html
{% extends "base.html" %}

{% block content %}
<section  id="app">
  <hr />
  <editables-list inline-template id="editables-list">
    <div>
      <div v-show="itemsLoaded && items.results.length > 0">
        <div v-for="item in items.results">
          <a :id="item.slug" :href="item.slug + '/'">
            <div class="title">
              [[item.title]]
            </div>
          </a>
          <a :href="'#tab-' + item.slug" name="tab-' + item.slug"></a>
        </div>
      </div>
    </div>
  </editables-list>
</section>
{% endblock %}

pages/templates/pages/package_list.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block content %}
<div ng-app="UploaderApp" ng-controller="UploaderCtrl">
    <h1>Upload theme</h1>
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-condensed custab">
            <thead>
                <th>Package name</th>
                <th>Created at</th>
                <th>Updated at</th>
                <th></th>
            </thead>
            <tbody>
                <tr ng-repeat="template in uploadedPackagelist">
                    <td>[% template.name %]<span style="font-size:11px;">[% template.slug.replace(template.name, '')|limitTo:10 %]</span></td>
                    <td>[% template.created_at|date %]</td>
                    <td>[% template.updated_at|date %]</td>
                    <td><a href="{% url 'uploaded_themes' %}[% template.slug %]/">Edit</a></td>
                </tr>
            </tbody>
        </table>
    </div>


    <div class="col-md-12">

        <div class="dropzone_area " dropzone="dropzoneConfig" style="margin-top:50px;text-align:center;padding:50px;background:#CCC">Drag and drop files here or click to upload</div>
    </div>
</div>

{% include "pages_upload_templates.html" %}

{% endblock content %}

pages/templates/pages/reading_template.html
{% extends "base.html" %}

{% block content %}
    <br>
    <a href="{% url 'progress:progress_view' sequence_slug=sequence.slug %}">
        Back to {{ sequence.slug }}
    </a>

    <h1>{{ element.page_element.title }}</h1>
    {% if element.page_element.text %}
        <hr>
        <p>{{ element.page_element.text|safe }}</p>
        <hr>
    {% endif %}

    {% if previous_element %}
        <a href="{% url 'progress:page_element_view' sequence_slug=sequence.slug rank=previous_element.rank %}">
            Previous
        </a>
    {% endif %}

    {% if next_element %}
        <a href="{% url 'progress:page_element_view' sequence_slug=sequence.slug rank=next_element.rank %}">
            Next
        </a>
    {% endif %}
    <br>

    {% if not progress %}
        <p>No progress yet!</p>
        <section id="app">
            <start-progress inline-template
                :sequence-slug="'{{ sequence.slug }}'"
                :user-username="'{{ request.user.username }}'"
                :element-rank="{{ element.rank }}">
                <div>
                    <button id="startProgress" @click="startProgress">Start Progress</button>
                    <p>Click the button to start tracking your progress.</p>
                </div>
            </start-progress>
        </section>
    {% else %}
        <section id="app">
            <viewing-timer inline-template
                :initial-duration="{{ viewing_duration_seconds }}"
                :rank="{{ element.rank }}"
                :sequence="'{{ sequence.slug }}'"
                :user="'{{ request.user.username }}'"
                :ping-interval="15">
                <div>
                    <label>Viewing Duration:</label> <span>[[ duration | formatDuration ]]</span>
                </div>
            </viewing-timer>
        </section>
    {% endif %}

{% endblock %}

pages/templates/pages/sequence_progress.html
{% extends "base.html" %}
{% load pages_tags %}

{% block content %}
<h2>{{ sequence.title }}</h2>
<section id="app">
    <sequence-items inline-template>
        <div>
            <div v-if="itemsLoaded">
                <ul>
                    {% for element in elements %}
                    <li>
                        <a href="{% url 'progress:page_element_view' sequence_slug=element.sequence.slug rank=element.rank %}">
                            {{ element_titles|get_item:element.rank }}</a>({{ element.rank }}) -
                        <template v-for="item in items.results">
                            <span v-if="item.rank === {{ element.rank }}">
                                [[ item.viewing_duration | formatDuration ]]
                            </span>
                        </template>
                        <span v-if="!items.results.some(item => item.rank === {{ element.rank }})">
                            No progress yet
                        </span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        {% include '_paginator.html' %}
        </div>
    </sequence-items>
</section>
{% endblock %}